In [1]:
import pandas as pd

In [2]:
df_pubs = pd.read_excel("./2023_Completo_redem_0304.xlsx")

In [4]:
df = pd.read_csv("df_res.csv")
print(f"Total de mensagens: {len(df)}")
df[df["min_distance"] > 0].sort_values("min_distance").head(10).reset_index().merge(
    df_pubs[["Message-ID", "Profile", "partido", "bloco"]],
    left_on="pub_id",
    right_on="Message-ID",
    how="left",
)

Total de mensagens: 91648

,index,message,min_distance,min_dist_document,doc_id,pub_id,all_distances,all_documents,all_ids,Message-ID,Profile,partido,bloco
0,10185,A que ponto chegamos quando é necessário desta...,0.248663,"Três parlamentares — Gayer, Valadares e Márcio...",25,18000181049515920,"[0.24866265058517456, 0.4200557768344879, 0.50...","['Três parlamentares — Gayer, Valadares e Márc...","['25', '22', '0']",18000181049515920,Bibo Nunes ????,PL,Oposição
1,90419,"??Nas fotos compartilhadas, você pode ver mome...",0.257881,Um em cada quatro parlamentares do GT desinfor...,22,18011087191931790,"[0.2578810155391693, 0.41665464639663696, 0.41...",['Um em cada quatro parlamentares do GT desinf...,"['22', '25', '0']",18011087191931790,Reginete Bispo,PT,Governo
2,9199,"??Aqui na Câmara dos Deputados, votei SIM e fo...",0.260605,"Três parlamentares — Gayer, Valadares e Márcio...",25,17926491020809450,"[0.2606047987937927, 0.3246850371360779, 0.417...","['Três parlamentares — Gayer, Valadares e Márc...","['25', '22', '0']",17926491020809450,Jefferson Campos,PL,Oposição
3,37017,"Estamos agora, no plenário do Senado para a Se...",0.272959,Um em cada quatro parlamentares do GT desinfor...,22,18097687645369472,"[0.27295932173728943, 0.4064810574054718, 0.50...",['Um em cada quatro parlamentares do GT desinf...,"['22', '25', '29']",18097687645369472,Carla Zambelli 22,PL,Oposição
4,21542,Há 8 meses temos alertado sobre a omissão dele...,0.275892,"Depois da eleição de Lula, Gayer passou a defe...",9,18000716960470480,"[0.2758917212486267, 0.390281081199646, 0.4466...","['Depois da eleição de Lula, Gayer passou a de...","['9', '0', '20']",18000716960470480,Sanderson,PL,Oposição
5,27389,??E OS DEVANEIOS DE LULA CONTINUAM…❌\n\nEm dua...,0.277302,"Depois da eleição de Lula, Gayer passou a defe...",9,18039449302540020,"[0.2773023247718811, 0.40181171894073486, 0.40...","['Depois da eleição de Lula, Gayer passou a de...","['9', '20', '0']",18039449302540020,Eduardo Girão,NOVO,Oposição
6,46118,"O Brasil como nação soberana, democrática, liv...",0.277721,"“Em nome da democracia, o Brasil acaba de ress...",0,18044055388552440,"[0.27772092819213867, 0.4220486283302307, 0.45...","['“Em nome da democracia, o Brasil acaba de re...","['0', '9', '20']",18044055388552440,Daniel Freitas,PL,Oposição
7,67018,Sobrinho de Bolsonaro é alvo de operação da PF...,0.282009,"Depois da eleição de Lula, Gayer passou a defe...",9,18010310146974140,"[0.2820090651512146, 0.39132970571517944, 0.43...","['Depois da eleição de Lula, Gayer passou a de...","['9', '0', '10']",18010310146974140,Lindbergh Farias,PT,Governo
8,9857,VITÓRIA DA OPOSIÇÃO!\n\nDurante votação da LDO...,0.286187,"Três parlamentares — Gayer, Valadares e Márcio...",25,18037998091615592,"[0.28618675470352173, 0.44649451971054077, 0.4...","['Três parlamentares — Gayer, Valadares e Márc...","['25', '22', '29']",18037998091615592,Alberto Fraga,PL,Oposição
9,61591,"Eu tenho buscado, em meu trabalho, zelar pela ...",0.287008,Um em cada quatro parlamentares do GT desinfor...,22,18020795725834160,"[0.2870076596736908, 0.4384881556034088, 0.441...",['Um em cada quatro parlamentares do GT desinf...,"['22', '0', '25']",18020795725834160,Dep. Icaro de Valmir,PL,Oposição

In [9]:
idx = 37017
# Acertos: 10185, 9199, 9857, 8460, 9272,  2513,   9563,9438, 46118
# tau = 0.307673
# Falsos positivos: 2513, 67018, 9863
# Talvez: 37017, 21542, 27389, 61591

print("POSTAGEM:")
print(df.iloc[idx]["message"])
print(
    f"Autor: {df_pubs[df_pubs['Message-ID'] == df.iloc[idx]['pub_id']]['Profile'].values[0]}"
)
print("=" * 100)
print("DOCUMENTO MAIS SIMILAR:")
print(df.iloc[idx]["min_dist_document"])

POSTAGEM:
Estamos agora, no plenário do Senado para a Sessão de Debates Temáticos sobre o aborto, convocada pelo Senador eduardogiraooficial.

Eu e meu marido, coronel_aginaldo não poderíamos encontrar com uma Senadora mais engajada na luta pela vida!

damaresalvesoficial1 fez história com seu incrível trabalho pelas mulheres, crianças, bebês, deficientes, idosos e vulneráveis no Ministério da Mulher, Família e Direitos Humanos de jairmessiasbolsonaro.

#AbortoNao
Autor: Carla Zambelli 22
====================================================================================================
DOCUMENTO MAIS SIMILAR:
Um em cada quatro parlamentares do GT desinformou sobre pautas de gênero e sexualidade desde o início do atual mandato. Entre eles está a deputada Simone Marquetto (MDB-SP), uma das coordenadoras da Frente Parlamentar Mista Contra o Aborto.

Em fevereiro deste ano, Marquetto alegou em publicação nas redes que uma nota técnica do Ministério da Saúde teria ampliado o acesso ao aborto no Brasil. Na realidade, o documento — que foi suspenso após ataques ao governo — apenas reforçava os casos de aborto já previstos em lei, que incluem gravidez com risco de vida à mãe, gestação resultante de estupro e anencefalia do feto.

In [10]:
pd.set_option("display.max_rows", None)

df_rank = (
    df.merge(df_pubs, left_on="pub_id", right_on="Message-ID", how="left")
    .groupby("Profile")
    .agg({"partido": "first", "pub_id": "count", "min_distance": "min"})
    .sort_values("min_distance")
)
df_rank.head(10)

                     partido  pub_id  min_distance
Profile
Bibo Nunes ????           PL     222      0.248663
Reginete Bispo            PT     307      0.257881
Jefferson Campos          PL     155      0.260605
Carla Zambelli 22         PL     746      0.272959
Sanderson                 PL     171      0.275892
Eduardo Girão           NOVO     358      0.277302
Daniel Freitas            PL     158      0.277721
Lindbergh Farias          PT     471      0.282009
Alberto Fraga             PL     335      0.286187
Dep. Icaro de Valmir      PL      65      0.287008

In [6]:
from embeders import OllamaEmbeddingFunction

embedder = OllamaEmbeddingFunction()

In [ ]:
import numpy as np


a = embedder("O céu é azul")
not_a = embedder("O céu não é azul")
diff = np.array(a) - np.array(not_a)

b = embedder("O céu é vermelho")
new_b = np.array(b) + diff


print(a)
print(not_a)
print(a - not_a)
print(b)
print(new_b)

# from embed vector to text
embedder.client.generate(model=embedder.model, prompt=new_b)