In [1]:
import pandas as pd

In [2]:
df_parls_raw = pd.read_csv("../../../../data/df_parlamentares_por_legislatura.csv")

In [3]:
df_parls = df_parls_raw[(df_parls_raw['idLegislatura'] == 56) & (df_parls_raw['nome'].notna())]

df_parls = df_parls[['id', 'nome']].drop_duplicates()

In [6]:

def is_in_divulgadores(name: str, divulgadores: str):
    return str(name).lower() in divulgadores.lower()


def count_in_divulgadores(name: str, divulgadores: str):
    return sum(1 for d in divulgadores if is_in_divulgadores(name, d))

df = pd.read_csv("./divulgadores_3.csv")

final = []
for i, parl in enumerate(df_parls['nome']):
    final.append({
        "nome": parl,
        "count": count_in_divulgadores(parl, df['divulgadores'])
    })

df_final = pd.DataFrame(final)
df_fn = df_final[df_final["count"] > 0]

print(
    f"Total de notícias analisadas: {len(df)}\n"
    f"Total de parlamentares: {len(df_final)}\nTotal de divulgadores: {len(df_fn)}\n% de divulgadores: {len(df_fn)/len(df_final)*100:.2f}%"
)

df_fn.sort_values(by="count", ascending=False)

Total de notícias analisadas: 685
Total de parlamentares: 637
Total de divulgadores: 23
% de divulgadores: 3.61%

                    nome  count
69             Bia Kicis      8
455          Osmar Terra      8
130      Daniel Silveira      4
172    Eduardo Bolsonaro      4
88        Carla Zambelli      3
481         Paulo Guedes      2
18             Alê Silva      1
404               Marcon      1
634             Zé Vitor      1
632              Zé Neto      1
621  WAGNER BACH MARTINS      1
562              Santini      1
559       Samuel Moreira      1
370            Luiz Lima      1
388       Marcelo Freixo      1
385          Marcelo Aro      1
52           Arthur Lira      1
291          João Campos      1
250      Gleisi Hoffmann      1
170      Eduardo Barbosa      1
105     Celso Russomanno      1
93          Carlos Jordy      1
636          Zeca Dirceu      1

In [36]:
pd.DataFrame(final).sort_values('count', ascending=False)

                      nome  count
0           Abílio Santana      0
428          Milton Coelho      0
421    Maurício Dziedricki      0
422  Mauro Benevides Filho      0
423            Mauro Lopes      0
..                     ...    ...
213  Félix Mendonça Júnior      0
214    Fernanda Melchionna      0
215         Fernando Borja      0
216  Fernando Coelho Filho      0
636            Zeca Dirceu      0

[637 rows x 2 columns]