In [17]:
import pandas as pd

In [18]:
df_parls = pd.read_csv('../../data/df_parl_detalhes.csv')
df_ird = pd.read_csv('../../outputs/df_equality_index.csv')
df_for_ird = pd.read_csv('../../outputs/df_for_ird.csv')
df_parls_per_legislatura = pd.read_csv('../../data/df_parlamentares_por_legislatura.csv')

In [19]:
df_parls_per_legislatura.loc[0]

id                                                           73909
uri              https://dadosabertos.camara.leg.br/api/v2/depu...
nome                                                           NaN
siglaPartido                                                   NaN
uriPartido       https://dadosabertos.camara.leg.br/api/v2/part...
siglaUf                                                         RS
idLegislatura                                                   52
urlFoto          https://www.camara.leg.br/internet/deputado/ba...
email                                                          NaN
Name: 0, dtype: object

In [20]:
df = df_ird.merge(df_parls_per_legislatura[['id', 'idLegislatura', 'nome', 'siglaPartido', 'siglaUf']], left_on=['legislatura', 'parl_id'], right_on=['idLegislatura', 'id'], how='left')
del df['id']
del df['idLegislatura']

df = df.merge(df_for_ird[['id', 'idLegislatura', 'F', 'M', 'branca', 'n_branca', 'parda', 'preta', 'amarela', 'indigena']], left_on=['legislatura', 'parl_id'], right_on=['idLegislatura', 'id'])
del df['id']
del df['idLegislatura']

In [21]:
df.to_csv('../../outputs/df_ird.csv', index=False)

In [22]:
df_ird.groupby('legislatura').sum()

               parl_id  weights
legislatura
52            48437439    626.0
53            65289555    636.0
54            82125839    671.0
55            87617770    623.0
56           103209033    613.0
57           108428811    595.0

In [33]:
df[df['nome'].isin(['MARIA DO ROSÁRIO','Maria do Rosário', 'Benedita da Silva', 'BENEDITA DA SILVA'])].sort_values(['legislatura', 'nome'])

,parl_id,legislatura,weights,nome,siglaPartido,siglaUf,F,M,branca,n_branca,parda,preta,amarela,indigena
719,74398,52,4.015394,MARIA DO ROSÁRIO,PT,RS,1,0,1,0,0,0,0,0
1656,74398,53,4.058711,MARIA DO ROSÁRIO,PT,RS,1,0,1,0,0,0,0,0
2051,73701,54,5.146337,BENEDITA DA SILVA,PT,RJ,1,0,0,1,0,1,0,0
2512,74398,54,3.730169,MARIA DO ROSÁRIO,PT,RS,1,0,1,0,0,0,0,0
2966,73701,55,4.652662,BENEDITA DA SILVA,PT,RJ,1,0,0,1,0,1,0,0
3586,74398,55,3.196921,MARIA DO ROSÁRIO,PT,RS,1,0,1,0,0,0,0,0
4053,73701,56,3.713232,Benedita da Silva,PT,RJ,1,0,0,1,0,1,0,0
4676,74398,56,2.235391,Maria do Rosário,PT,RS,1,0,1,0,0,0,0,0
5094,73701,57,3.038531,Benedita da Silva,PT,RJ,1,0,0,1,0,1,0,0
5455,74398,57,1.828216,Maria do Rosário,PT,RS,1,0,1,0,0,0,0,0

In [42]:
df[(df['indigena']==1) & (df['legislatura']==57)]

,parl_id,legislatura,weights,nome,siglaPartido,siglaUf,F,M,branca,n_branca,parda,preta,amarela,indigena
5126,206018,57,2.587629,Célia Xakriabá,PSOL,MG,1,0,0,1,0,0,0,1
5365,220640,57,2.587629,Juliana Cardoso,PT,SP,1,0,0,1,0,0,0,1
5616,220579,57,2.587629,Silvia Waiãpi,PL,AP,1,0,0,1,0,0,0,1
5622,220643,57,2.587629,Sônia Guajajara,PSOL,SP,1,0,0,1,0,0,0,1